### ISSUE TITLE
How to specify nested data properties

### ISSUE THREAD

**Issue by sarfraznawaz2005** [PeakTai/vue-verify#1]
Suppose I have data like this:

data: {
   xyx : "xyz",
   foo : {
         bar : { "baz":1 }
   }
}

I know I can access `xyz` easily in `this.$verify` but how do I specify nested values like `foo.bar.baz` ?

thanks

**Comment by sarfraznawaz2005** [comment]
Nevermind, I figured out.

**Comment by cannap** [comment]
Hi how you made this? i tried 

x: { x: {} } then i tried 'x.y' but nothing happens

thx
